# Generated by Django 5.0.6 on 2024-07-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashish',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
