# Generated by Django 5.0.6 on 2024-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ashish_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashish',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
